import { defineCollection } from "astro:content";
import { glob } from "astro/loaders";
import { z } from 'astro/zod';
import { docsLoader, i18nLoader } from "@astrojs/starlight/loaders";
import { docsSchema, i18nSchema } from "@astrojs/starlight/schema";

export const collections = {
  docs: defineCollection({ loader: docsLoader(), schema: docsSchema() }),
  blog: defineCollection({
    loader: glob({ pattern: "**/*.{md,mdx}", base: "./src/content/blog" }),
    schema: ({ image }) => z.object({
      title: z.string(),
      description: z.string(),
      publishedAt: z.coerce.date(),
      updatedAt: z.coerce.date().optional(),
      author: z.string().default("Steel Team"),
      category: z.string().default("News"),
      featured: z.boolean().default(false),
      placeholder: z.boolean().default(false),
      socialImage: z.object({
        src: image(),
        alt: z.string().min(1),
      }).optional(),
    }),
  }),
  i18n: defineCollection({ loader: i18nLoader(), schema: i18nSchema({
      extend: z.object({
        langFlag: z.string().optional(),
        langName: z.string().optional(),
        searchPlaceholder: z.string().optional(),
        devWarningText: z.string().optional(),
        discordLabel: z.string().optional(),
        githubLabel: z.string().optional(),
        download: z.string().optional(),
        githubHref: z.string().optional(),
        version: z.string().optional(),
        latestVersion: z.string().optional(),
        needOlderVersion: z.string().optional(),
        viewPreviousVersions: z.string().optional(),
        olderVersions: z.string().optional(),
        forMinecraft: z.string().optional(),
        releasedDate: z.string().optional(),
        tracker: z.string().optional(),
        trackerLabel: z.string().optional(),
        // Download page
        "download.meta.description": z.string().optional(),
        "download.pill": z.string().optional(),
        "download.title": z.string().optional(),
        "download.titleHighlight": z.string().optional(),
        "download.subtitle": z.string().optional(),
        "download.latest.badge": z.string().optional(),
        "download.latest.minecraft": z.string().optional(),
        "download.latest.description": z.string().optional(),
        "download.platform.label": z.string().optional(),
        "download.installGuide.text": z.string().optional(),
        "download.installGuide.link": z.string().optional(),
        "download.archive.title": z.string().optional(),
        "download.archive.count.one": z.string().optional(),
        "download.archive.count.other": z.string().optional(),
        "download.archive.minecraft": z.string().optional(),
        "download.empty.title": z.string().optional(),
        "download.empty.text": z.string().optional(),
        // Implementation tracker
        "tracker.meta.title": z.string().optional(),
        "tracker.meta.description": z.string().optional(),
        "tracker.title": z.string().optional(),
        "tracker.titleHighlight": z.string().optional(),
        "tracker.subtitle": z.string().optional(),
        "tracker.stats.totalBehaviors": z.string().optional(),
        "tracker.stats.totalEntries": z.string().optional(),
        "tracker.stats.complete": z.string().optional(),
        "tracker.stats.partial": z.string().optional(),
        "tracker.stats.unimplemented": z.string().optional(),
        "tracker.progress.title": z.string().optional(),
        "tracker.progress.byClasses": z.string().optional(),
        "tracker.progress.byEntries": z.string().optional(),
        "tracker.progress.ariaLabel": z.string().optional(),
        "tracker.metric.surface": z.string().optional(),
        "tracker.metric.behaviors": z.string().optional(),
        "tracker.tooltip.notStarted": z.string().optional(),
        "tracker.tab.blocks": z.string().optional(),
        "tracker.tab.items": z.string().optional(),
        "tracker.tab.entities": z.string().optional(),
        "tracker.entryLabel.blocks": z.string().optional(),
        "tracker.entryLabel.items": z.string().optional(),
        "tracker.entryLabel.entities": z.string().optional(),
        "tracker.search.placeholder": z.string().optional(),
        "tracker.filter.all": z.string().optional(),
        "tracker.filter.todo": z.string().optional(),
        "tracker.results.showing": z.string().optional(),
        "tracker.results.class.one": z.string().optional(),
        "tracker.results.class.other": z.string().optional(),
        "tracker.results.entries": z.string().optional(),
        "tracker.badge.todo": z.string().optional(),
        "tracker.results.more": z.string().optional(),
        "tracker.noResults.title": z.string().optional(),
        "tracker.noResults.hint": z.string().optional(),
      }),
  }) }),
};
